// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHE.API.Data;

#nullable disable

namespace PHE.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829183213_AddSiteVisitFields")]
    partial class AddSiteVisitFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHE.API.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountForPlots")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Application_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedLayoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedLayoutMapPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedLayoutNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoTagPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOTPVerified")
                        .HasColumnType("bit");

                    b.Property<string>("KMLFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("LayoutAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutYesNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OTPExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Peth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlotsApplicableForThisNoc")
                        .HasColumnType("int");

                    b.Property<string>("PropertyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatBaraPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShowAmountAsPerNoOfPlots")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SiteRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteVisitEstimateDocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteVisitGeoTagPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNocPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalEstimateAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalPlots")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scrutiny_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applicants", (string)null);
                });

            modelBuilder.Entity("PHE.API.Models.ApplicantsLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("AadhaarNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountForPlots")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Application_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedLayoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedLayoutMapPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedLayoutNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoTagPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KMLFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("LayoutAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutYesNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlotsApplicableForThisNoc")
                        .HasColumnType("int");

                    b.Property<string>("PropertyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatBaraPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShowAmountAsPerNoOfPlots")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SiteRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteVisitEstimateDocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteVisitGeoTagPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNocPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalEstimateAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalPlots")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scrutiny_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ApplicantsLog", (string)null);
                });

            modelBuilder.Entity("PHE.API.Models.JEApplication", b =>
                {
                    b.Property<int>("SrNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SrNo"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedLayoutMap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JagechaAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ManjurLayoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManjurLayoutNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilakataKramanka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatBaraUtara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrutinyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SrNo");

                    b.ToTable("JEApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
